baseurl: /json-api
source: .
destination: ./public

# github pages we cannot customize
lsi: false
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
incremental: false
gist:
  noscript: false

# customize github pages
quiet: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  auto_id_prefix: auto-id-
  auto_id_stripping: true
  template: '' # cannot customize
  math_engine: mathjax # cannot customize
  syntax_highligher: rouge # cannot customize

plugins:
  - jekyll-redirect-from

exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss

port: 9876

collections:
  format:
    output: true
  errors:
    output: true
  profiles:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: format
    values:
      layout: page
      show_sidebar: true
      is_spec_page: true
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: error
      is_spec_page: false
      show_sidebar: false
  - scope:
      path: ""
      type: "errors"
    values:
      layout: error
      is_spec_page: false
      show_sidebar: false
  - scope:
      path: "*/*/*/index.md"
      type: "profiles"
    values:
      layout: profile
      is_spec_page: false
      show_sidebar: true

latest_version: 1.0
excerpt_separator: ""
announcement: ""

navigation:
- title: JSON API
  url: /json-api/
- title: Specification
  url: /json-api/format/
- title: Extensions
  url: /json-api/extensions/
- title: Recommendations
  url: /json-api/recommendations/
- title: Examples
  url: /json-api/examples/
- title: Implementations
  url: /json-api/implementations/
- title: FAQ
  url: /json-api/faq/
- title: About
  url: /json-api/about/

quicklinks:
- title: View the specification
  url: /json-api/format/


profile_categories:
  - Pagination
  # these are some other potential categories.
  # Uncomment them if you're adding a profile in one of these categories.
  # - Filtering
  # - Actions/Hypermedia
  # - Data Modeling
  # - Deep Querying
